sudo: required
services:
  - docker

before_install:
  - docker build -t marbor1/fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run marbor1/fib-test npm run test:ci

after_success:
  - docker build -t marbor1/multi-client ./client
  - docker build -t marbor1/multi-nginx ./nginx
  - docker build -t marbor1/multi-server ./server
  - docker build -t marbor1/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push marbor1/multi-client
  - docker push marbor1/multi-nginx
  - docker push marbor1/multi-server
  - docker push marbor1/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-672307187164"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
